# -*- coding: utf-8 -*-
"""OTIF V1 — catalog constants."""
from __future__ import annotations

OT_VERSION_V1 = "ot_v1"
OT_GENERATION_VERSION_V1 = "ot_v1_gen"
OT_REGISTRY_VERSION_V1 = "otreg_v1"
OT_SOURCE_CONTRACT_VERSION_V1 = "ot_v1"

SEVERITY_CRITICAL = "critical"
SEVERITY_WARNING = "warning"
SEVERITY_INFORMATIONAL = "informational"

SEVERITIES_V1 = frozenset(
    {SEVERITY_CRITICAL, SEVERITY_WARNING, SEVERITY_INFORMATIONAL}
)

VIS_EXPOSE = "expose"
VIS_SUPPRESS = "suppress"
VIS_DEFER = "defer"

STABILITY_STABLE = "stable"
STABILITY_FORMING = "forming"
STABILITY_IMPROVING = "improving"
STABILITY_DETERIORATING = "deteriorating"
STABILITY_UNKNOWN = "unknown"

LIFECYCLE_ACTIVE = "active"
LIFECYCLE_CLEARED = "cleared"
LIFECYCLE_SUPPRESSED = "suppressed"

__all__ = [
    "OT_VERSION_V1",
    "OT_GENERATION_VERSION_V1",
    "OT_REGISTRY_VERSION_V1",
    "OT_SOURCE_CONTRACT_VERSION_V1",
    "SEVERITY_CRITICAL",
    "SEVERITY_WARNING",
    "SEVERITY_INFORMATIONAL",
    "SEVERITIES_V1",
    "VIS_EXPOSE",
    "VIS_SUPPRESS",
    "VIS_DEFER",
    "STABILITY_STABLE",
    "STABILITY_FORMING",
    "STABILITY_IMPROVING",
    "STABILITY_DETERIORATING",
    "STABILITY_UNKNOWN",
    "LIFECYCLE_ACTIVE",
    "LIFECYCLE_CLEARED",
    "LIFECYCLE_SUPPRESSED",
]
