# -*- coding: utf-8 -*-
"""Follow-on ALTER: align fresh Alembic PostgreSQL to current production physical schema.

Revision ID: f10altparity01
Revises: f9altlclose01
Create Date: 2026-09-11

Birth CREATEs stay truthful. Surviving C-class revisions stay untouched.
This revision only matches live create_all-era physical leftovers:
types, nullability, server defaults, one FK, and indexes.

commercial_decision_commitments remains DEPRECATE (not created).
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "f10altparity01"
down_revision: Union[str, Sequence[str], None] = "f9altlclose01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"

    if is_pg:
        # stores.integration_source is TEXT on production (create_all / helper).
        # SQLite cannot ALTER COLUMN TYPE; VARCHAR vs TEXT is not enforced there.
        op.alter_column(
            "stores",
            "integration_source",
            existing_type=sa.String(length=64),
            type_=sa.Text(),
            existing_nullable=True,
        )

        # Production create_all left an FK; reconstructed ADD did not.
        op.create_foreign_key(
            "stores_merchant_user_id_fkey",
            "stores",
            "merchant_users",
            ["merchant_user_id"],
            ["id"],
        )
        op.alter_column("abandoned_carts", "vip_mode", server_default=None)
        op.alter_column("business_findings", "as_of_key", server_default=None)
        op.alter_column("business_findings", "confidence", server_default=None)
        op.alter_column("business_findings", "confidence_score", server_default=None)
        op.alter_column("business_findings", "diagnostics_json", server_default=None)
        op.alter_column("business_findings", "engine_version", server_default=None)
        op.alter_column("business_findings", "evidence_json", server_default=None)
        op.alter_column("business_findings", "fingerprint", server_default=None)
        op.alter_column("business_findings", "is_current", server_default=None)
        op.alter_column("business_findings", "lifecycle_events_json", server_default=None)
        op.alter_column("business_findings", "lifecycle_state", server_default=None)
        op.alter_column("business_findings", "lifecycle_version", server_default=None)
        op.alter_column("business_findings", "merchant_id", server_default=None)
        op.alter_column("business_findings", "merchant_summary", server_default=None)
        op.alter_column("business_findings", "payload_json", server_default=None)
        op.alter_column("business_findings", "reasoning_json", server_default=None)
        op.alter_column("business_findings", "recommended_action", server_default=None)
        op.alter_column("business_findings", "routing_json", server_default=None)
        op.alter_column("business_findings", "severity", server_default=None)
        op.alter_column("business_findings", "title", server_default=None)
        op.alter_column("business_findings", "visibility_state", server_default=None)
        op.alter_column("cart_line_snapshots", "cart_id", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "as_of_key", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "commercial_domain", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "commercial_relevance_input_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "comparison_subject_id", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "comparison_subject_type", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "confidence_input_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "conflicting_facts_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "contract_version", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "contradicting_evidence_count", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "evidence_coverage", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "failure_reason", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "generation_version", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "input_fingerprint", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "is_current", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "known_facts_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "minimum_sample_size", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "missing_source_domains_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "pattern_direction", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "pattern_type", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "prohibited_claims_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "required_source_domains_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "rule_version", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "sample_size", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "significance_input_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "source_contributions_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "source_domains_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "source_record_ids_json", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "subject_id", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "subject_type", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "supporting_evidence_count", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "synthesis_fingerprint", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "synthesis_summary_key", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "synthesis_version", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "time_window_key", server_default=None)
        op.alter_column("commerce_intelligence_syntheses", "unknown_facts_json", server_default=None)
        op.alter_column("commercial_guidance_records", "as_of_key", server_default=None)
        op.alter_column("commercial_guidance_records", "eligibility_id", server_default=None)
        op.alter_column("commercial_guidance_records", "eligibility_status", server_default=None)
        op.alter_column("commercial_guidance_records", "generation_version", server_default=None)
        op.alter_column("commercial_guidance_records", "guidance_fingerprint", server_default=None)
        op.alter_column("commercial_guidance_records", "guidance_scope", server_default=None)
        op.alter_column("commercial_guidance_records", "guidance_version", server_default=None)
        op.alter_column("commercial_guidance_records", "input_fingerprint", server_default=None)
        op.alter_column("commercial_guidance_records", "is_current", server_default=None)
        op.alter_column("commercial_guidance_records", "knowledge_reference_ids_json", server_default=None)
        op.alter_column("commercial_guidance_records", "known_facts_json", server_default=None)
        op.alter_column("commercial_guidance_records", "prohibited_claims_json", server_default=None)
        op.alter_column("commercial_guidance_records", "rationale_code", server_default=None)
        op.alter_column("commercial_guidance_records", "rationale_summary", server_default=None)
        op.alter_column("commercial_guidance_records", "rule_version", server_default=None)
        op.alter_column("commercial_guidance_records", "source_contract_version", server_default=None)
        op.alter_column("commercial_guidance_records", "subject_id", server_default=None)
        op.alter_column("commercial_guidance_records", "subject_type", server_default=None)
        op.alter_column("commercial_guidance_records", "unknown_facts_json", server_default=None)
        op.alter_column("dashboard_snapshots", "payload_json", server_default=None)
        op.alter_column("dashboard_snapshots", "status", server_default=None)
        op.alter_column("dashboard_snapshots", "version", server_default=None)
        op.alter_column("dashboard_snapshots_archive", "payload_json", server_default=None)
        op.alter_column("dashboard_snapshots_archive", "status", server_default=None)
        op.alter_column("dashboard_snapshots_archive", "version", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "as_of_key", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "completeness", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "confidence_notes_json", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "confidence_score", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "confidence_version", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "conflicting_signals", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "consistency", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "content_hash", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "evaluator_version", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "factors_json", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "freshness", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "missing_sources_json", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "sample_size", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "source_diversity", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "subject_id", server_default=None)
        op.alter_column("evidence_confidence_evaluations", "subject_type", server_default=None)
        op.alter_column("evidence_truth_materialization_runs", "accounting_json", server_default=None)
        op.alter_column("evidence_truth_materialization_runs", "batch_limit", server_default=None)
        op.alter_column("evidence_truth_materialization_runs", "composer_version", server_default=None)
        op.alter_column("evidence_truth_materialization_runs", "error_json", server_default=None)
        op.alter_column("evidence_truth_materialization_runs", "mode", server_default=None)
        op.alter_column("evidence_truth_materialization_runs", "status", server_default=None)
        op.alter_column("evidence_truth_shadow_artifacts", "artifact_version", server_default=None)
        op.alter_column("evidence_truth_shadow_artifacts", "composer_version", server_default=None)
        op.alter_column("evidence_truth_shadow_artifacts", "lineage_json", server_default=None)
        op.alter_column("evidence_truth_shadow_artifacts", "payload_json", server_default=None)
        op.alter_column("evidence_truth_shadow_artifacts", "source_ref", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "as_of_key", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "blocking_conditions_json", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "eligibility_reason", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "eligibility_version", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "fingerprint", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "knowledge_count", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "knowledge_ids_json", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "required_knowledge_count", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "subject_id", server_default=None)
        op.alter_column("guidance_eligibility_evaluations", "subject_type", server_default=None)
        op.alter_column("guidance_routes", "as_of_key", server_default=None)
        op.alter_column("guidance_routes", "generation_version", server_default=None)
        op.alter_column("guidance_routes", "guidance_key", server_default=None)
        op.alter_column("guidance_routes", "input_fingerprint", server_default=None)
        op.alter_column("guidance_routes", "is_current", server_default=None)
        op.alter_column("guidance_routes", "route_fingerprint", server_default=None)
        op.alter_column("guidance_routes", "route_role", server_default=None)
        op.alter_column("guidance_routes", "route_scope", server_default=None)
        op.alter_column("guidance_routes", "routing_context_digest", server_default=None)
        op.alter_column("guidance_routes", "routing_rationale_code", server_default=None)
        op.alter_column("guidance_routes", "routing_registry_version", server_default=None)
        op.alter_column("guidance_routes", "routing_rule_version", server_default=None)
        op.alter_column("guidance_routes", "routing_version", server_default=None)
        op.alter_column("guidance_routes", "source_contract_version", server_default=None)
        op.alter_column("guidance_routes", "subject_id", server_default=None)
        op.alter_column("guidance_routes", "subject_type", server_default=None)
        op.alter_column("guidance_routes", "surface_registry_version", server_default=None)
        op.alter_column("knowledge_statements", "as_of_key", server_default=None)
        op.alter_column("knowledge_statements", "assembly_window", server_default=None)
        op.alter_column("knowledge_statements", "confidence_level", server_default=None)
        op.alter_column("knowledge_statements", "fingerprint", server_default=None)
        op.alter_column("knowledge_statements", "knowledge_version", server_default=None)
        op.alter_column("knowledge_statements", "statement", server_default=None)
        op.alter_column("knowledge_statements", "subject_id", server_default=None)
        op.alter_column("knowledge_statements", "subject_type", server_default=None)
        op.alter_column("merchant_presentations", "action_affordance", server_default=None)
        op.alter_column("merchant_presentations", "action_label_key", server_default=None)
        op.alter_column("merchant_presentations", "as_of_key", server_default=None)
        op.alter_column("merchant_presentations", "disclaimer_key", server_default=None)
        op.alter_column("merchant_presentations", "evidence_state", server_default=None)
        op.alter_column("merchant_presentations", "failure_reason", server_default=None)
        op.alter_column("merchant_presentations", "generation_version", server_default=None)
        op.alter_column("merchant_presentations", "guidance_id", server_default=None)
        op.alter_column("merchant_presentations", "guidance_key", server_default=None)
        op.alter_column("merchant_presentations", "headline_key", server_default=None)
        op.alter_column("merchant_presentations", "headline_text", server_default=None)
        op.alter_column("merchant_presentations", "input_fingerprint", server_default=None)
        op.alter_column("merchant_presentations", "is_current", server_default=None)
        op.alter_column("merchant_presentations", "known_facts_json", server_default=None)
        op.alter_column("merchant_presentations", "language_code", server_default=None)
        op.alter_column("merchant_presentations", "merchant_relevance_key", server_default=None)
        op.alter_column("merchant_presentations", "merchant_relevance_text", server_default=None)
        op.alter_column("merchant_presentations", "presentation_fingerprint", server_default=None)
        op.alter_column("merchant_presentations", "presentation_rule_version", server_default=None)
        op.alter_column("merchant_presentations", "presentation_version", server_default=None)
        op.alter_column("merchant_presentations", "primary_statement_key", server_default=None)
        op.alter_column("merchant_presentations", "primary_statement_text", server_default=None)
        op.alter_column("merchant_presentations", "route_role", server_default=None)
        op.alter_column("merchant_presentations", "route_scope", server_default=None)
        op.alter_column("merchant_presentations", "source_contract_version", server_default=None)
        op.alter_column("merchant_presentations", "status_label_key", server_default=None)
        op.alter_column("merchant_presentations", "subject_id", server_default=None)
        op.alter_column("merchant_presentations", "subject_type", server_default=None)
        op.alter_column("merchant_presentations", "supporting_statement_key", server_default=None)
        op.alter_column("merchant_presentations", "supporting_statement_text", server_default=None)
        op.alter_column("merchant_presentations", "template_key", server_default=None)
        op.alter_column("merchant_presentations", "template_version", server_default=None)
        op.alter_column("merchant_presentations", "unknown_facts_json", server_default=None)
        op.alter_column("product_catalog_entries", "currency", server_default=None)
        op.alter_column("product_evidence_bundles", "as_of_key", server_default=None)
        op.alter_column("product_evidence_bundles", "bundle_version", server_default=None)
        op.alter_column("product_evidence_bundles", "computation_version", server_default=None)
        op.alter_column("product_evidence_bundles", "fingerprint", server_default=None)
        op.alter_column("product_evidence_bundles", "source_count", server_default=None)
        op.alter_column("product_evidence_items", "content_hash", server_default=None)
        op.alter_column("product_evidence_items", "lineage_json", server_default=None)
        op.alter_column("product_evidence_items", "source_record_id", server_default=None)
        op.alter_column("product_evidence_items", "subject_id", server_default=None)
        op.alter_column("product_evidence_items", "subject_type", server_default=None)
        op.alter_column("product_evidence_items", "trend_window", server_default=None)
        op.alter_column("product_hesitation_mappings", "cart_id", server_default=None)
        op.alter_column("product_hesitation_mappings", "mapping_source", server_default=None)
        op.alter_column("product_metric_values", "computation_version", server_default=None)
        op.alter_column("product_metric_values", "content_hash", server_default=None)
        op.alter_column("product_metric_values", "source_signal_type", server_default=None)
        op.alter_column("product_metric_values", "stable_identity_key", server_default=None)
        op.alter_column("product_metric_values", "value", server_default=None)
        op.alter_column("product_metric_values", "window_code", server_default=None)
        op.alter_column("product_metric_values", "window_end_key", server_default=None)
        op.alter_column("product_metric_values", "window_start_key", server_default=None)
        op.alter_column("product_purchase_mappings", "cart_id", server_default=None)
        op.alter_column("product_signal_events", "cart_id", server_default=None)
        op.alter_column("product_signal_events", "identity_tier", server_default=None)
        op.alter_column("product_signal_events", "session_id", server_default=None)
        op.alter_column("product_trend_values", "as_of_key", server_default=None)
        op.alter_column("product_trend_values", "computation_version", server_default=None)
        op.alter_column("product_trend_values", "content_hash", server_default=None)
        op.alter_column("product_trend_values", "current_value", server_default=None)
        op.alter_column("product_trend_values", "delta_abs", server_default=None)
        op.alter_column("product_trend_values", "metric_family", server_default=None)
        op.alter_column("product_trend_values", "previous_value", server_default=None)
        op.alter_column("product_trend_values", "stable_identity_key", server_default=None)
        op.alter_column("stores", "exit_intent_template_mode", server_default=None)
        op.alter_column("stores", "exit_intent_template_tone", server_default=None)
        op.alter_column("stores", "recovery_attempts", server_default=None)
        op.alter_column("stores", "recovery_delay", server_default=None)
        op.alter_column("stores", "recovery_delay_unit", server_default=None)
        op.alter_column("stores", "template_mode", server_default=None)
        op.alter_column("stores", "template_tone", server_default=None)
        op.alter_column("stores", "widget_name", server_default=None)
        op.alter_column("stores", "widget_primary_color", server_default=None)
        op.alter_column("stores", "widget_style", server_default=None)
        op.alter_column("surface_compositions", "accounting_outcome", server_default=None)
        op.alter_column("surface_compositions", "as_of_key", server_default=None)
        op.alter_column("surface_compositions", "composition_version", server_default=None)
        op.alter_column("surface_compositions", "confidence", server_default=None)
        op.alter_column("surface_compositions", "destination_surfaces_json", server_default=None)
        op.alter_column("surface_compositions", "duplicate_group", server_default=None)
        op.alter_column("surface_compositions", "failure_reason", server_default=None)
        op.alter_column("surface_compositions", "fingerprint", server_default=None)
        op.alter_column("surface_compositions", "freshness_state", server_default=None)
        op.alter_column("surface_compositions", "generation_version", server_default=None)
        op.alter_column("surface_compositions", "input_fingerprint", server_default=None)
        op.alter_column("surface_compositions", "is_current", server_default=None)
        op.alter_column("surface_compositions", "lifecycle", server_default=None)
        op.alter_column("surface_compositions", "merchant_value", server_default=None)
        op.alter_column("surface_compositions", "owns_full_explanation", server_default=None)
        op.alter_column("surface_compositions", "presentation_intent", server_default=None)
        op.alter_column("surface_compositions", "priority", server_default=None)
        op.alter_column("surface_compositions", "source_contract_version", server_default=None)
        op.alter_column("surface_compositions", "source_id", server_default=None)
        op.alter_column("surface_compositions", "source_lineage_json", server_default=None)
        op.alter_column("surface_compositions", "source_type", server_default=None)
        op.alter_column("surface_compositions", "suppression_rules_json", server_default=None)
        op.alter_column("surface_compositions", "surface_registry_version", server_default=None)
        op.alter_column("surface_compositions", "urgency", server_default=None)
        op.alter_column("surface_compositions", "visibility", server_default=None)
        op.alter_column("surface_compositions", "visibility_reason", server_default=None)

        op.alter_column("db_ready_operational_snapshots", "last_top_substage_elapsed_ms", server_default=sa.text('0'))
        op.alter_column("db_ready_operational_snapshots", "last_top_substage_queries", server_default=sa.text('0'))
        op.alter_column("db_ready_operational_snapshots", "last_top_substage_sql_ms", server_default=sa.text('0'))
        op.alter_column("db_ready_operational_snapshots", "restart_first_dashboard_duration_ms", server_default=sa.text('0'))
        op.alter_column("db_ready_operational_snapshots", "restart_survival_result", server_default=sa.text("'pending'"))
        op.alter_column("db_ready_operational_snapshots", "restart_survival_timing", server_default=sa.text("'unknown'"))
        op.alter_column("db_ready_operational_snapshots", "stage_classifications_json", server_default=sa.text("'[]'"))
        op.alter_column("db_ready_operational_snapshots", "startup_warm_duration_ms", server_default=sa.text('0'))
        op.alter_column("db_ready_operational_snapshots", "startup_warm_status", server_default=sa.text("'not_started'"))
        op.alter_column("db_ready_operational_snapshots", "top_substages_json", server_default=sa.text("'[]'"))
        op.alter_column("merchant_users", "current_plan", server_default=sa.text("'starter'"))
        op.alter_column("merchant_users", "plan_source", server_default=sa.text("'manual'"))
        op.alter_column("merchant_users", "plan_status", server_default=sa.text("'active'"))
        op.alter_column("stores", "merchant_automation_mode", server_default=sa.text("'manual'"))
        op.alter_column("stores", "settings_notify_recovery_success", server_default=sa.text('true'))
        op.alter_column("stores", "settings_notify_vip", server_default=sa.text('true'))
        op.alter_column("stores", "settings_notify_whatsapp_failure", server_default=sa.text('true'))
        op.alter_column("stores", "vip_enabled", server_default=sa.text('true'))
        op.alter_column("stores", "vip_notify_enabled", server_default=sa.text('true'))
        op.alter_column("stores", "whatsapp_mode", server_default=sa.text("'cartflow_managed'"))
        op.alter_column("stores", "whatsapp_recovery_enabled", server_default=sa.text('true'))
        op.alter_column("stores", "widget_enabled", server_default=sa.text('true'))

        op.alter_column("commercial_guidance_records", "confidence_level", existing_nullable=False, nullable=True)
        op.alter_column("commercial_guidance_records", "eligible_actions_json", existing_nullable=False, nullable=True)
        op.alter_column("commercial_guidance_records", "forbidden_actions_json", existing_nullable=False, nullable=True)
        op.alter_column("commercial_guidance_records", "knowledge_id", existing_nullable=False, nullable=True)
        op.alter_column("commercial_guidance_records", "knowledge_type", existing_nullable=False, nullable=True)
        op.alter_column("commercial_guidance_records", "merchant_objective", existing_nullable=False, nullable=True)
        op.alter_column("commercial_guidance_records", "source_knowledge_fingerprint", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "is_current", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "known_facts_json", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "prohibited_claims_json", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "source_contract_version", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "source_domains_json", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "source_fingerprint", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "source_rule_key", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "source_rule_version", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "source_synthesis_id", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "source_synthesis_key", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "source_type", existing_nullable=False, nullable=True)
        op.alter_column("knowledge_statements", "unknown_facts_json", existing_nullable=False, nullable=True)
    # SQLite helper: skip DROP/SET DEFAULT and ALTER NULL; types already loose.

    op.drop_index("ix_abandoned_carts_store_status_last_seen", table_name="abandoned_carts")
    op.drop_index("ix_cart_recovery_logs_context_status", table_name="cart_recovery_logs")
    op.drop_index("ix_cart_recovery_logs_recovery_key", table_name="cart_recovery_logs")
    op.drop_index("ix_cisyn_store_current", table_name="commerce_intelligence_syntheses")
    op.drop_index("ix_cisyn_store_pattern_current", table_name="commerce_intelligence_syntheses")
    op.drop_index("ix_cisyn_store_subject_current", table_name="commerce_intelligence_syntheses")
    op.drop_index("ix_cisyn_store_key_current", table_name="commerce_intelligence_syntheses")
    op.drop_index("ix_cisyn_store_state_current", table_name="commerce_intelligence_syntheses")
    op.drop_index("ix_cisyn_rule_subject_window", table_name="commerce_intelligence_syntheses")
    op.drop_index("ix_commercial_guidance_records_knowledge_id", table_name="commercial_guidance_records")
    op.drop_index("ix_commercial_guidance_records_knowledge_type", table_name="commercial_guidance_records")
    op.drop_index("ix_commercial_guidance_current_grain", table_name="commercial_guidance_records")
    op.drop_index("ix_dashboard_snapshots_store_type_generated", table_name="dashboard_snapshots")
    op.drop_index("ix_dashboard_snapshots_archive_store_type_gen", table_name="dashboard_snapshots_archive")
    op.drop_index("ix_et_mat_runs_run_id", table_name="evidence_truth_materialization_runs")
    op.drop_index("ix_guidance_routes_guidance_surface", table_name="guidance_routes")
    op.drop_index("ix_guidance_routes_store_guidance", table_name="guidance_routes")
    op.drop_index("ix_guidance_routes_store_subject", table_name="guidance_routes")
    op.drop_index("ix_guidance_routes_store_surface_current", table_name="guidance_routes")
    op.drop_index("ix_knowledge_statements_is_current", table_name="knowledge_statements")
    op.drop_index("ix_knowledge_statements_source_rule_key", table_name="knowledge_statements")
    op.drop_index("ix_knowledge_statements_source_synthesis_id", table_name="knowledge_statements")
    op.drop_index("ix_lifecycle_closure_records_cart_id", table_name="lifecycle_closure_records")
    op.drop_index("ix_lifecycle_closure_records_session_id", table_name="lifecycle_closure_records")
    op.drop_index("ix_lifecycle_closure_records_store_slug", table_name="lifecycle_closure_records")
    op.drop_index("ix_merchant_presentations_route_current", table_name="merchant_presentations")
    op.drop_index("ix_merchant_presentations_store_route", table_name="merchant_presentations")
    op.drop_index("ix_merchant_presentations_store_subject", table_name="merchant_presentations")
    op.drop_index("ix_merchant_presentations_store_surface_current", table_name="merchant_presentations")
    op.drop_index("ix_product_evidence_bundles_evidence_bundle_id", table_name="product_evidence_bundles")
    op.drop_index("ix_recovery_schedules_store_slug_status_due", table_name="recovery_schedules")
    op.drop_index("ix_simulation_runs_simulation_run_id", table_name="simulation_runs")

    op.create_index("ix_business_findings_category_id", "business_findings", ['category_id'])
    op.create_index("ix_business_findings_expires_at", "business_findings", ['expires_at'])
    op.create_index("ix_business_findings_fingerprint", "business_findings", ['fingerprint'])
    op.create_index("ix_business_findings_generated_at", "business_findings", ['generated_at'])
    op.create_index("ix_business_findings_merchant_id", "business_findings", ['merchant_id'])
    op.create_index("ix_business_findings_product_id", "business_findings", ['product_id'])
    op.create_index("ix_business_findings_visibility_state", "business_findings", ['visibility_state'])
    op.create_index("ix_dashboard_snapshots_expires_at", "dashboard_snapshots", ['expires_at'])
    op.create_index("ix_dashboard_snapshots_generated_at", "dashboard_snapshots", ['generated_at'])
    op.create_index("ix_dashboard_snapshots_snapshot_type", "dashboard_snapshots", ['snapshot_type'])
    op.create_index("ix_dashboard_snapshots_status", "dashboard_snapshots", ['status'])
    op.create_index("ix_dashboard_snapshots_store_slug", "dashboard_snapshots", ['store_slug'])
    op.create_index("ix_dashboard_snapshots_archive_generated_at", "dashboard_snapshots_archive", ['generated_at'])
    op.create_index("ix_dashboard_snapshots_archive_snapshot_type", "dashboard_snapshots_archive", ['snapshot_type'])
    op.create_index("ix_dashboard_snapshots_archive_store_slug", "dashboard_snapshots_archive", ['store_slug'])
    op.create_index("ix_simulation_event_ledger_simulated_at", "simulation_event_ledger", ['simulated_at'])
    op.create_index("ix_simulation_event_ledger_store_slug", "simulation_event_ledger", ['store_slug'])


def downgrade() -> None:
    raise NotImplementedError("f10altparity01 is alignment-only")

